# Use the official Nginx image
FROM nginx:latest

# Copy the custom Nginx configuration file into the container
# COPY nginx.conf /etc/nginx/nginx.conf

# Copy the Laravel application from the PHP container
COPY . /var/www/html 

# Expose port 80
EXPOSE 80
